# Generated by Django 3.2 on 2022-07-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220716_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='articles', to='blog.Category', verbose_name='دسته بندی'),
        ),
    ]
